<a href="https://colab.research.google.com/github/Yhemisol/4B1b/blob/master/ML1_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. Tutorial Setup
!pip install -U scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 17.9 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [ ]:
!python -m pip show scikit-learn

Name: scikit-learn
Version: 1.4.2
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: /usr/local/lib/python3.10/dist-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: bigframes, fastai, imbalanced-learn, librosa, mlxtend, qudida, sklearn-pandas, yellowbrick


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving tutorial.zip to tutorial.zip


In [ ]:
!ls

sample_data  tutorial.zip


In [ ]:
import zipfile
import os

# Specify the zip file name
zip_file_path = './tutorial.zip'

# Specify the destination folder
extract_path = './'

# Unzip the file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# List the contents of the extracted folder
extracted_folder = os.path.splitext(os.path.basename(zip_file_path))[0]
print("Folder extracted to:", os.path.join(extract_path, extracted_folder))

Folder extracted to: ./tutorial


In [ ]:
!ls tutorial

data  skeletons  solutions  working_with_text_data.rst


In [ ]:
!python tutorial/data/languages/fetch_data.py

Streaming output truncated to the last 5000 lines.
Writing short_paragraphs/it/it_0079.txt
Writing short_paragraphs/it/it_0080.txt
Writing short_paragraphs/it/it_0081.txt
Writing short_paragraphs/it/it_0082.txt
Writing short_paragraphs/it/it_0083.txt
Writing short_paragraphs/it/it_0084.txt
Writing short_paragraphs/it/it_0085.txt
Writing short_paragraphs/it/it_0086.txt
Writing short_paragraphs/it/it_0087.txt
Writing short_paragraphs/it/it_0088.txt
Writing short_paragraphs/it/it_0089.txt
Writing short_paragraphs/it/it_0090.txt
Writing short_paragraphs/it/it_0091.txt
Writing short_paragraphs/it/it_0092.txt
Writing paragraphs/it/it_0008.txt
Writing short_paragraphs/it/it_0093.txt
Writing short_paragraphs/it/it_0094.txt
Writing short_paragraphs/it/it_0095.txt
Writing short_paragraphs/it/it_0096.txt
Writing short_paragraphs/it/it_0097.txt
Writing short_paragraphs/it/it_0098.txt
Writing short_paragraphs/it/it_0099.txt
Writing short_paragraphs/it/it_0100.txt
Writing short_paragraphs/it/it_0101

In [ ]:
#2. Loading the 20 newsgroups dataset

categories = ['alt.atheism', 'soc.religion.christian',
              'comp.graphics', 'sci.med']

In [ ]:
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train',
    categories=categories, shuffle=True, random_state=42)

In [ ]:
twenty_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [ ]:
len(twenty_train.data)

2257

In [ ]:
print("\n".join(twenty_train.data[0].split("\n")[:3]))

From: sd345@city.ac.uk (Michael Collier)
Subject: Converting images to HP LaserJet III?
Nntp-Posting-Host: hampton


In [ ]:
print(twenty_train.target_names[twenty_train.target[0]])

comp.graphics


In [ ]:
twenty_train.target[:10]

array([1, 1, 3, 3, 3, 3, 3, 2, 2, 2])

In [ ]:
for t in twenty_train.target[:10]:
    print(twenty_train.target_names[t])

comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med


In [ ]:
# 3. Extracting features from text files

from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_counts.shape

(2257, 35788)

In [ ]:
count_vect.vocabulary_.get(u'algorithm')

4690

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

(2257, 35788)

In [ ]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(2257, 35788)

In [ ]:
# 4. Training a classifier

from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, twenty_train.target)

In [ ]:
docs_new = ['God is love', 'OpenGL on the GPU is fast']
X_new_counts = count_vect.transform(docs_new)
X_new_tfidf = tfidf_transformer.transform(X_new_counts)

predicted = clf.predict(X_new_tfidf)

for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, twenty_train.target_names[category]))

'God is love' => soc.religion.christian
'OpenGL on the GPU is fast' => comp.graphics


In [ ]:
!pip install clf

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for clf: filename=clf-0.5.7-py3-none-any.whl size=6376 sha256=730dd2cc8188cba734cd2fefff2e572287f631cf4b7a64cc4c774717d2445815
  Stored in directory: /root/.cache/pip/wheels/b1/1c/3c/b3925ba2fd9f1bfdadce8c468bd9ff0a82e1e2c595c3705c41
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=aa9e53fa8042d3649543eb599a0cff5e21846410f7b0efb80a14d286550a154b
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
Successfully built clf docopt


In [ ]:
# Language identification

%run tutorial/skeletons/exercise_01_language_train_model.py paragraphs/

              precision    recall  f1-score   support

          ar       1.00      1.00      1.00        33
          de       1.00      0.99      0.99        75
          en       0.98      1.00      0.99        84
          es       1.00      0.98      0.99        65
          fr       1.00      1.00      1.00        65
          it       1.00      0.95      0.97        37
          ja       0.95      1.00      0.97        39
          nl       1.00      1.00      1.00        24
          pl       1.00      1.00      1.00        33
          pt       1.00      1.00      1.00        55
          ru       1.00      1.00      1.00        33

    accuracy                           0.99       543
   macro avg       0.99      0.99      0.99       543
weighted avg       0.99      0.99      0.99       543

[[33  0  0  0  0  0  0  0  0  0  0]
 [ 0 74  1  0  0  0  0  0  0  0  0]
 [ 0  0 84  0  0  0  0  0  0  0  0]
 [ 0  0  0 64  0  0  1  0  0  0  0]
 [ 0  0  0  0 65  0  0  0  0  0  0]
 [ 0  0